title: B-Kolaru
author: Dele Kolaru
email: b.kolaru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experienced Project Manager with a demonstrated history of working in the information technology and services industry. Skilled in Management, Network Administration, Business Support System (BSS), Java and Cloud technologies (Azure and Google). Strong community and social services professional with a masterâ€™s degree in Engineering Management from the University of Ottawa

# social links
github_username:  b-kolaru # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
